### ISSUE TITLE
DMGPartition::readRun new logic is incorrect

### ISSUE THREAD

**Issue by tomkoen** [darlinghq/darling-dmg#78]
The new logic introduced in this [commit](https://github.com/darlinghq/darling-dmg/commit/a8fbdb0229ba27a2795a32e43a9710a6a4552e43) by @jief666 throws an exception whilst the older code works fine mounting the same dmg image.

Exception is thrown here:
```cpp
if (dec < count)
   throw io_error("Error decompressing stream");
```

[Image to reproduce](https://www.dropbox.com/s/a6raknyrggrnrzl/qt-creator-opensource-mac-x86_64-4.5.1.dmg?dl=0)

**Comment by jief666** [comment]
I probably put that check a bit quick. It might be possible that the compressed buffer is bigger than the uncompressed one, so dec would be < count.
Usually, read method returns what they could read even if it's less than count. So that should be ok to remove that check. But DMGPartition::read should be modified too, to be able to return less than count. (maybe it was handled and I removed it :-).
In my memory, I put that because I had infinite loop in DMGPartition::read
So you try just removing the throw ?
I'll talk about that to my old friend the live debugger !

**Comment by kleuter** [comment]
io_error is still thrown after all the patches

**Comment by tomkoen** [comment]
io_error is still thrown after all the patches
